bob/bob.t

When using regular expressions, $ and _ will match differently if the
user uses \W or \w - these tests test for these edge cases.

Adds tests for regex edge cases

---

largest-series-product/series_product.t

As part of the work to have consistency between tracks as in https://github.com/exercism/todo/issues/104 and https://github.com/exercism/todo/issues/13. Comments are in individual commit messages.

largest-series-product corner cases

---

largest-series-product/series_product.t

The slices functions is an internal implementation details and thus the
test case for the largest-series-product problem should not be concerned
with testing it.
Its presence may cause students to falsely think that their solution has
to use this function, instead of the alternative implementation of only
iterating through the digits once.
The slices tests are already well-covered by the series exercise already
existing in this track.
If it is desired to give hints on how to approach this problem (which
was one advantage of having the slices test), then consider including a
hints file and/or directory in the largest-series-product directory.
This PR arises from discussion in
https://github.com/exercism/x-common/issues/192

largest-series-product: Do not test slices

---

sum-of-multiples/Example.pm
sum-of-multiples/sum_of_multiples.t

Fixes #110
This removes the assumption that the multiples default to 3 and 5 if not provided.

Do not assume default values

---

README.md

Copied from exercism.io's ATTRIBUTION.md so it's here when the files that file refers to go away.
a step in fixing https://github.com/exercism/exercism.io/issues/3112.

add the attribution for the icon that the Perl foundation let us use

---

exercises/bob/Example.pm
exercises/bob/bob.t

Updated due to https://github.com/exercism/x-common/issues/441, plus a user was confused about hexadecimal escape sequences.

Match bob to canonical data

---

README.md
cpanfile

Path::Tiny will be needed for travis to successfully run canonical data tests from the generator.

Add Path::Tiny to cpanfile

---

.travis.yml
bin/cpanfile
bin/exercise-gen.pl
docs/INSTALLATION.md
exercises/bob/bob.t
exercises/hello-world/hello-world.t
templates/test.mustache

Unfortunately I had encountered some issues when using Data::Dump on canonical-data in some other exercises with the generator. JSON will likely be more reliable to work with.
JSON::PP is in core from 5.14 onwards, so I'm bumping the minimum up to 5.14.

Use JSON formatted canonical-data

---

exercises/bob/bob.t
exercises/hello-world/hello-world.t
exercises/leap/leap.t
exercises/luhn/luhn.t
exercises/phone-number/phone-number.t
templates/test.mustache

This is to prevent canonical-data tests from causing Travis to fail, so that changes can be made before canonical-data is updated.

Mark canonical-data tests as todo

---

exercises/bob/.meta/exercise-data.yaml
exercises/bob/.meta/solutions/Bob.pm
exercises/bob/Bob.pm
exercises/bob/bob.t
exercises/clock/.meta/exercise-data.yaml
exercises/clock/.meta/solutions/Clock.pm
exercises/clock/Clock.pm
exercises/clock/clock.t
exercises/hello-world/.meta/exercise-data.yaml
exercises/hello-world/.meta/solutions/HelloWorld.pm
exercises/hello-world/HelloWorld.pm
exercises/hello-world/hello-world.t
exercises/leap/.meta/exercise-data.yaml
exercises/leap/.meta/solutions/Leap.pm
exercises/leap/Leap.pm
exercises/leap/leap.t
exercises/luhn/.meta/exercise-data.yaml
exercises/luhn/.meta/solutions/Luhn.pm
exercises/luhn/Luhn.pm
exercises/luhn/luhn.t
exercises/phone-number/.meta/exercise-data.yaml
exercises/phone-number/.meta/solutions/PhoneNumber.pm
exercises/phone-number/PhoneNumber.pm
exercises/phone-number/phone-number.t
templates/module.mustache
templates/test.mustache

Now that we no longer have modules named `Example`, we can `use` modules directly and import their subroutines in a standard fashion.

use Exporter for exporting subroutines from modules

---

exercises/leap/.meta/exercise-data.yaml
exercises/leap/.meta/solutions/Leap.pm
exercises/leap/Leap.pm
exercises/leap/leap.t

The previous test was doing a string comparison on whether the returned value was either `1` or `0`. With this change, it should be possible to pass the test by returning any value which would be considered either true or false (Perl 5 does not have a boolean type).

Improve truth/falsehood test for Leap

---

bin/exercise-gen.pl

This allows the `--all` argument to be in any position, and prevents exercises from accidentally being generated multiple times.

Add argument set to generator script

---

exercises/grains/.meta/exercise-data.yaml
exercises/grains/.meta/solutions/Grains.pm
exercises/grains/Grains.pm
exercises/grains/grains.t

`is` is for string comparison and is not reliable for large numbers.

Replace `is` with `cmp_ok` for numeric comparison in grains

---

docs/RESOURCES.md

Trying to run the command with dash results in "Couldn't find module or a distribution".

Fix RESOURCES.md installation instruction

---

docs/INSTALLATION.md

The URL in the docs no longer links to the relevant page, and there hasn't been a new version of DWIM Perl in almost 7 years.

Remove mention of DWIM Perl from documentation

---

bin/exercise-gen.pl

This is to add functionality which already exists in the Perl 6 exercise generator.
The generator will run the configlet to update readme files as needed.
The generator will warn if it cannot find the configlet or problem-specifications directory.

Add readme generation to generator

---

.travis.yml
cpanfile
t/generated-tests.t

Yath (Yet Another Test Harness) [can be thought of as a more powerful alternative to prove](https://metacpan.org/pod/App::Yath). Adding it to travis to ensure that there are no issues running the exercise tests with either yath or prove.

Run tests with both prove and yath

---

.travis.yml

The jobs flag on prove hides the output of the directives flag, so we can't see if any tests have been skipped in the logs.

Move prove jobs flag to yath

---

exercises/anagram/anagram.t

Fixing these quotes prints Anagram.pm rather than $module.pm.

anagram: Fix a pair of quotes in anagram.t

---

exercises/custom-set/.meta/solutions/CustomSet.pm
exercises/custom-set/CustomSet.pm
exercises/custom-set/custom-set.t

For this PR I haven't written a test generator yet, as it was recommended in #241.

custom-set: Stub, order of methods, rename some methods

---

.perltidyrc
exercises/bob/bob.t
exercises/hello-world/hello-world.t
exercises/leap/leap.t

A small change to prevent wrapping of lines with trailing comments. Seems unnecessary to do so in my opinion.

Add ignore-side-comment-lengths to perltidy

---

exercises/clock/cpanfile

Can be installed via the command line with a simple `cpm install --with-{recommends,suggests}`
I considered opting for one of the simpler OOP modules, but ended up going with Moo as the recommended due to its ubiquity and available resources.

Add cpanfile with recommends/suggests for OO modules

---

.travis.yml

Trusty was the default, but it seems to have flipped to Xenial and is causing the builds to fail for older perl versions.

Add trusty dist to travis

---

exercises/clock/.meta/exercise-data.yaml
exercises/clock/Clock.pm

*someone* (me) forgot to update the stub for this exercise to be appropriate for Moo. The new method is not needed.

Make Clock stub Moo appropriate

---

.gitignore
.gitmodules
.travis.yml

This is to make it easier to follow the instructions in bin/README.md.  After cloning, you can do `git submodule update --init --recursive` to fetch the problem-specifications repo.
I also updated .gitignore to ignore files installed by carton.  That was another thing I noticed while starting to work on converting exercises to use the generator.
Thank you for considering this PR!

Add problem-specifications submodule

---

lib/Exercism/Generator.pm

This is to ensure the track .perltidyrc file is used if the generator is run from other locations.

Add explicit .perltidyrc path to generator

---

config.json

Both of these exercises have been deprecated in problem-specifications in favor of all-your-base, which is already implemented on this track.

Deprecate trinary and hexadecimal

---

exercises/grains/.meta/exercise-data.yaml
exercises/grains/grains.t

We don't need BigFloat magic here as Grains.pm will always return bigints.
This should fix #239 and #240.

Avoid extra number conversions

---

templates/test.mustache

The utf8 flag on JSON results in the following error in combination with Test2::V0:
malformed UTF-8 character in JSON string
https://metacpan.org/pod/JSON::PP#ENCODING/CODESET-FLAG-NOTES
Canonical data typically does not have non-ascii characters so this is currently, for the most part, not an issue, but an exercise is currently in development to work with UTF-8.

Use non-utf8 JSON object for test data

---

bin/README.md
docs/ABOUT.md
docs/INSTALLATION.md
docs/LEARNING.md
docs/RESOURCES.md
docs/TESTS.md

We've defined a [specification for Markdown files](https://github.com/exercism/docs/blob/main/contributing/standards/markdown.md) to be applied Exercism-wide. This standard includes, amongst others, the following two rules:
- All files must start start with a level-1 heading (`# Some heading text`)
- No heading may decend a level greater than one below the previous (e.g. `## may only be followed by ###, not ####`)
This PR applies the above two rules to the Markdown documents in this repo. 
https://github.com/exercism/v3-launch/issues/17

[v3] Update Markdown files to latest spec

---

exercises/practice/robot-name/.meta/exercise-data.yaml
exercises/practice/robot-name/robot-name.t

Tests for `robot-name` were changed in PR https://github.com/exercism/perl5/pull/364, but they were done outside of the exercise generator. The changes have now been incorporated into the exercise data, and the generator run to perform other updates.

Include robot-name updates in generator data

---

lib/Exercism/Generator.pm
t/files/generated-tests.t

Done according to the spec in https://github.com/exercism/configlet/issues/198. Expects `include` to either not exist or be true.

Update generator to accept old and new tests.toml formats

---

exercises/practice/meetup/.docs/instructions.md
exercises/practice/meetup/.meta/exercise-data.yaml
exercises/practice/meetup/.meta/solutions/Meetup.pm
exercises/practice/meetup/Meetup.pm
exercises/practice/meetup/meetup.t

Input is now given as strings matching the examples in the description e.g. `Teenth Wednesday of May 2022`

Update meetup to transform input as noted in exercise description

---

exercises/practice/binary-search-tree/.meta/exercise-data.yaml
exercises/practice/binary-search-tree/binary-search-tree.t

@exercism/reviewers Subtests are currently not supported in the test runner. The new loop also ensures the tests run in the expected order.

Refactor binary-search-tree to not use subtests

---

config.json

No longer needed to differentiate, since Perl 6 became Raku

Reference Perl 5 as "Perl"

---

exercises/practice/roman-numerals/roman-numerals.t

This reorders the test data to match the upstream, which changed the order to increase numerically.
This gets the generator tests to pass, so that we can rebase the two configlet-based PRs onto main, and get them merged.

Reorder data in roman-numerals test

---

exercises/practice/largest-series-product/.docs/instructions.md
exercises/practice/largest-series-product/.docs/introduction.md
exercises/practice/largest-series-product/.meta/tests.toml
exercises/practice/largest-series-product/largest-series-product.t

The largest-series-product exercise has been overhauled as part of a project to make practice exercises more consistent and friendly.
For more context, please see the discussion in the forum, as well as the pull request that updated the exercise in the problem-specifications repository:
- https://forum.exercism.org/t/new-project-making-practice-exercises-more-consistent-and-human-across-exercism/3943
- https://github.com/exercism/problem-specifications/pull/2246 
Note that we have deprecated and removed two test cases that deal with the multiplicative identity (also referred to as an empty product). By doing this we were able to avoid talking about this at all, which makes this exercise much more approachable.
----
If you approve this pull request, I will eventually merge it. However, if …

Sync largest-series-product docs with problem-specifications

---

exercises/practice/gigasecond/.docs/introduction.md
exercises/practice/linked-list/.docs/instructions.md

In line with Exercism's spec, we're ensuring that all admonition fences are demarcated with four tildes (`~~~~`) across all repositories. We will be following up with an org-wide script that can be used to keep this consistent. [Problem Specifications](https://github.com/exercism/problem-specifications) has already been updated.
We'll automatically merge this a week from now, but feel free to merge beforehand!
- Spec: https://exercism.org/docs/building/markdown/markdown#h-special-blocks-sometimes-called-admonitions
- Meta issue: https://github.com/exercism/exercism/issues/6705

Convert backtick (`) admonition fences to tildes (~)

---

.github/workflows/exercises.yml
.github/workflows/generator.yml

This PR updates GitHub Actions runners to a specific version.
This ensures that the workflow will always run on the same runner, which makes your build _stable_.
The PR updates the *-latest version with the current version, as specified in https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources.
See https://exercism.org/docs/building/github/gha-best-practices#h-pin-test-runners-to-version for more information.

CI: pin GitHub Actions runners

---

.github/workflows/exercises.yml
.github/workflows/generator.yml

This PR updates GitHub Actions workflows to a specific version.
This ensures that the workflow will always run the same code, which makes your build _stable_.
It will also prevent a potential security issue where a tag could be replaced by a malicious commit without consumers being aware of it.
The PR updates each non-SHA based workflow reference with the SHA of the referenced version/tag, so the current behavior should not change.
See https://exercism.org/docs/building/github/gha-best-practices#h-pin-actions-to-shas for more information.

CI: pin GitHub Actions workflows

---

exercises/practice/matrix/.meta/solutions/lib/Matrix.pm
exercises/practice/matrix/.meta/template-data.yaml
exercises/practice/matrix/lib/Matrix.pm
exercises/practice/matrix/t/matrix.t

This exercise had been implemented with an object oriented interface since before I started maintaining, but it does not seem like a good fit for this exercise.

Switch matrix from OO to functions

---

config.json

UTF8 problem to be resolved in test runner.
Fixed in https://github.com/exercism/perl5-test-runner/pull/86

Set micro-blog as wip

---

config.json
exercises/practice/armstrong-numbers/.docs/instructions.md
exercises/practice/armstrong-numbers/.meta/config.json
exercises/practice/armstrong-numbers/.meta/solutions/lib/ArmstrongNumbers.pm
exercises/practice/armstrong-numbers/.meta/solutions/t/armstrong-numbers.t
exercises/practice/armstrong-numbers/.meta/template-data.yaml
exercises/practice/armstrong-numbers/.meta/tests.toml
exercises/practice/armstrong-numbers/lib/ArmstrongNumbers.pm
exercises/practice/armstrong-numbers/t/armstrong-numbers.t

I don't know if this is the right approach for this exercise. Does the code need some type checking?

Add armstrong-numbers exercise

---

config.json
exercises/practice/dnd-character/.docs/instructions.md
exercises/practice/dnd-character/.docs/introduction.md
exercises/practice/dnd-character/.meta/config.json
exercises/practice/dnd-character/.meta/solutions/lib/DndCharacter.pm
exercises/practice/dnd-character/.meta/solutions/t/dnd-character.t
exercises/practice/dnd-character/.meta/template-data.yaml
exercises/practice/dnd-character/.meta/tests.toml
exercises/practice/dnd-character/lib/DndCharacter.pm
exercises/practice/dnd-character/t/dnd-character.t

I purposely left the stub very empty, in case students want to use Moo or something else.

Add dnd-character exercise
