exercism/perl5

crypto-square/Example.pm
crypto-square/crypto.t

This brings this exercise into conformity with the README and the other exercises.

Fixes exercism/xperl5#88

---

sum-of-multiples/sum_of_multiples.t

Addresses https://github.com/exercism/todo/issues/60.

Add missing sum of multiples test

---

docs/ABOUT.md

I was shown exercism.io a few days ago and was very impressed. I looked at http://exercism.io/languages/perl5 and saw the following text, which I thought we might as well get rid of by doing as the stub text suggests: 
We're missing a short introduction about the language.
Help us by adding a file called ABOUT.md in the docs/ directory of the repo at https://github.com/exercism/xperl5.

Added ABOUT.md with some content recommended by exercism author.

---

scrabble-score/scrabble.t

Update scrabble word oxyphenbutazone

---

config.json

Adjust regex to look for files that end in `.t` rather than `t`

Fix test_pattern

---

exercises/rna-transcription/rna.t

Change the name  for nucleobases, not nucleosides

---

exercises/hamming/Example.pm
exercises/hamming/hamming.t

Now we must die if the strings are of different lengths
Fixes #81

change requirement for different lengths

---

docs/TOOLS.md

For #75
Just cover the usual basics, PBP as a good base reference (nobody agree on all the rules, but hey, nobody ever agree on *everything*), and the classic perlcritic/perltidy tools.

mention PBP, perltidy and perlcritic

---

config.json
exercises/all-your-base/Example.pm
exercises/all-your-base/all-your-base.t

Tests are based on the json file in x-common

add all-your-base problem

---

.github/stale.yml

Enable Probot

---

docs/TESTS.md

fixes #139 by using consistent filenames

fixing bob typos in testing doc

---

exercises/bob/Bob.pm
exercises/bob/Example.pm
exercises/bob/bob.t
exercises/bob/example.yaml

Using the generator in https://github.com/exercism/perl5/pull/148

Generate bob

---

.travis.yml
README.md
bin/exercise-gen.pl
cpanfile
lib/Exercism/Generator.pm
t/generated-tests.t
templates/test.mustache

Perl 5 port of the Perl 6 generator module.

Create generator module and test generated exercises

---

docs/ABOUT.md

ref: exercism/meta#85
closes: #177

Complies and removed ending whitespace.

---

exercises/hello-world/.meta/exercise-data.yaml
exercises/hello-world/hello-world.t
lib/Exercism/Generator.pm

Based on feedback/changes made for Perl 6 in https://github.com/exercism/perl6/issues/297

Ignore canonical data for hello-world

---

bin/exercise-gen.pl
lib/Exercism/Generator.pm
t/generated-tests.t

Brain must have still been in Perl 6 mode when I started writing this... 🤦

Add strict and warnings pragmas to generator

---

exercises/bob/.meta/exercise-data.yaml
exercises/bob/bob.t
exercises/clock/.meta/exercise-data.yaml
exercises/clock/clock.t
exercises/grains/grains.t
exercises/hello-world/.meta/exercise-data.yaml
exercises/hello-world/hello-world.t
exercises/leap/.meta/exercise-data.yaml
exercises/leap/leap.t
exercises/luhn/luhn.t
exercises/phone-number/phone-number.t
templates/test.mustache

I don't see the benefit of having it in the template

Remove exercise variable

---

bin/exercise-gen.pl

Tiny refactor for a happier `Perl::Critic`

Refactor generator warnings

---

exercises/luhn/.meta/exercise-data.yaml
exercises/luhn/Luhn.pm
exercises/luhn/luhn.t

Make behavior consistent with leap

Allow any truthy/falsey return value for luhn

---

exercises/bob/.meta/exercise-data.yaml
exercises/bob/bob.t
exercises/clock/clock.t
exercises/grade-school/grade-school.t
exercises/grains/grains.t
exercises/hello-world/.meta/exercise-data.yaml
exercises/hello-world/hello-world.t
exercises/leap/.meta/exercise-data.yaml
exercises/leap/leap.t
exercises/luhn/luhn.t
exercises/nucleotide-count/nucleotide-count.t
exercises/phone-number/phone-number.t
exercises/raindrops/raindrops.t
exercises/rna-transcription/rna-transcription.t
exercises/roman-numerals/roman-numerals.t
exercises/two-fer/two-fer.t
templates/test.mustache

This will allow for easy local installation and usage of modules with cpm/carton

Add local/lib for modules

---

exercises/difference-of-squares/.meta/solutions/Squares.pm
exercises/difference-of-squares/difference_of_squares.t

In exercise difference-of-squares, renamed `square_of_sums` to `square_of_sum`.

difference-of-squares: renamed square_of_sums to square_of_sum

---

exercises/twelve-days/.meta/solutions/TwelveDays.pm
exercises/twelve-days/README.md
exercises/twelve-days/song.t

Update twelve-days to match specification

---

README.md
exercises/binary-search/binary-search.t
exercises/binary-search/cpanfile
exercises/grains/.meta/exercise-data.yaml
exercises/grains/cpanfile
exercises/grains/grains.t
exercises/largest-series-product/cpanfile
exercises/largest-series-product/series_product.t
exercises/minesweeper/cpanfile
exercises/minesweeper/minesweeper.t
exercises/nucleotide-count/.meta/exercise-data.yaml
exercises/nucleotide-count/cpanfile
exercises/nucleotide-count/nucleotide-count.t
exercises/phone-number/.meta/exercise-data.yaml
exercises/phone-number/phone-number.t
exercises/series/cpanfile
exercises/series/series.t

Closes https://github.com/exercism/perl5/issues/253

Replace Test::Fatal with Test2::Tools::Exception

---

.travis.yml
exercises/grains/.meta/exercise-data.yaml
exercises/grains/.meta/solutions/Grains.pm
exercises/grains/grains.t

Fix example solution so that it uses bignum.

grains: Fail test when result is imprecise (fixes #239)

---

exercises/hello-world/.meta/exercise-data.yaml
exercises/hello-world/hello-world.t
templates/test.mustache

Set up as a stacked pull request: https://github.com/robinbentley/stacked-pull-request

Test2 [PART 4]: Test2::V0 on generator

---

exercises/grains/.meta/exercise-data.yaml
exercises/grains/.meta/solutions/Grains.pm
exercises/grains/README.md
exercises/grains/grains.t

I replaced BigInt with BigFloat, as with BigInt the test will report NaN if the module happens to return a float, which could be confusing.

Generate grains with Test2::V0

---

exercises/luhn/.meta/exercise-data.yaml
exercises/luhn/luhn.t

This contains test data which has not yet been merged, to remove a non-ASCII character which was causing issues with running the test.
https://github.com/exercism/problem-specifications/pull/1523

Generate luhn with Test2::V0

---

exercises/hello-world/hello-world.t

This is for the version matching on https://tracks.exercism.io/perl5

Add version to hello-world for tracks dashboard

---

README.md

This should have been part of #327 - sorry I didn't think of it!  This updates the README so others will not have to go hunting for the instructions to do the same!  It also updates the problem-specifications submodule to the latest.  Thanks for considering this PR!

Add submodule instructions; update submodule

---

bin/fetch-configlet

Fix #342.
This is being fixed in all languages.

Fix configlet fetching

---

bin/exercise-gen.pl
cpanfile
exercises/hello-world/.meta/solutions/HelloWorld.pm
exercises/hello-world/HelloWorld.pm
exercises/hello-world/hello-world.t
exercises/leap/.meta/exercise-data.yaml
exercises/leap/.meta/solutions/Leap.pm
exercises/leap/Leap.pm
exercises/leap/leap.t
lib/Exercism/Generator.pm
t/generated-tests.t
templates/module.mustache
templates/test.mustache

* Adjust JSON spacing
* Use platform agnostic file paths
* Use lib::gitroot to determine the project root

Generator tweaks

---

exercises/etl/.meta/exercise-data.yaml
exercises/etl/ETL.pm
exercises/etl/README.md
exercises/etl/etl.t
templates/test.mustache

Generate etl with toml

---

bin/exercise-gen.pl

It doesn't  make sense for these two to run together right now, at least not in the generator's current state.

Decouple configlet from exercise generator

---

exercises/practice/etl/etl.t
exercises/practice/gigasecond/gigasecond.t
exercises/practice/nucleotide-count/nucleotide-count.t
exercises/practice/pascals-triangle/pascals-triangle.t
exercises/practice/phone-number/phone-number.t

Run the generator to update test descriptions

Update test descriptions

---

exercises/practice/hello-world/HelloWorld.pm

Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46

🤖 Simplify `hello-world` stub

---

exercises/practice/clock/clock.t
t/files/generated-tests.t

Partial tweak for addressing failing check.

Tidy clock and trim unneeded test arg

---

.gitignore

(Also remove the user choice artifacts)

Add the problem-specifications for generator

---

exercises/practice/accumulate/accumulate.t

Run updated perltidy on accumulate

---

.github/workflows/generator.yml
README.md
bin/exercise-gen.pl
lib/Exercism/Generator.pm
t/files/generated-tests.t

Closes https://github.com/exercism/perl5/issues/471

Update README and generator problem specs details

---

t/files/generated-tests.t

This should fix the workflow failure.

Reset Data::Dmp setting when checking generated files

---

exercises/practice/nucleotide-count/.docs/instructions.md
exercises/practice/nucleotide-count/.meta/config.json
exercises/practice/nucleotide-count/.meta/solutions/NucleotideCount.pm
exercises/practice/nucleotide-count/.meta/template-data.yaml
exercises/practice/nucleotide-count/.meta/tests.toml

Added a small refactor of the example solution as void context maps are generally frowned upon.

Update nucleotide-count docs

---

.github/workflows/exercises.yml

I want to make an effort to use the latest features in Perl. Some of these features are present in older versions of Perl, but are not enabled by default.
The goal of this is to enable these features, and in future drop older versions of Perl which do not support them.

Add signatures and postderef features to github workflow

---

config.json

I would like to make updates to the track, and pending work for these exercises is a blocker.

Set Test2::Bundle::More exercises as WIP

---

docs/TESTS.md
exercises/shared/.docs/tests.md

The linked doc provides a bit of a gentler introduction to is() and other parts of the .t files. I think this will be helpful for perl newbies.

Add an introductory document about Test2

---

config.json

Pulled from [Perl.org](https://www.perl.org/about.html)
1. **Vibrant community:** _Be they Mongers, Monks, or residents of Planet Perl - they are eager to share knowledge and tips._
2. **Embeddable:**  _The Perl interpreter can be embedded into a wide variety of systems like web servers and databases._
3. **Multi-paradigm:** _Code your way. Full support for functional, procedural, and object-oriented programming._
4. **Easily Extensible:** _Leverage over 25, 000 modules available on CPAN, or write your very own for distribution.",
5. **1st class text & Unicode:** _Powerful tools for HTML XML, and all manner of natural languages. Full Unicode support baked in._
6. **Duct-tape of the internet:** _Underpinning the web since the beginning. The general purpose language for getting things …

[Track]: Added Key Features and Icons.

---

exercises/concept/booking-up-for-beauty/.docs/hints.md
exercises/concept/booking-up-for-beauty/.docs/instructions.md
exercises/concept/booking-up-for-beauty/.docs/introduction.md
exercises/concept/booking-up-for-beauty/.docs/introduction.md.tpl

The instructions were largely copied from [the Go exercise](https://github.com/exercism/go/blob/main/exercises/concept/booking-up-for-beauty/.docs/instructions.md).

Adding documentation to the booking-up-for-beauty concept exercise

---

exercises/concept/inventory-management/.docs/instructions.md

corrected typo

---

concepts/basics/about.md
concepts/basics/introduction.md

Add booleans to scalar description

---

config.json
exercises/practice/reverse-string/.docs/instructions.append.md
exercises/practice/reverse-string/.docs/instructions.md
exercises/practice/reverse-string/.docs/introduction.md
exercises/practice/reverse-string/.meta/config.json
exercises/practice/reverse-string/.meta/solutions/lib/ReverseString.pm
exercises/practice/reverse-string/.meta/solutions/t/reverse-string.t
exercises/practice/reverse-string/.meta/template-data.yaml
exercises/practice/reverse-string/.meta/tests.toml
exercises/practice/reverse-string/lib/ReverseString.pm
exercises/practice/reverse-string/t/reverse-string.t

brian d foy writes about [perl's handling of grapheme clusters](https://www.effectiveperlprogramming.com/2011/06/treat-unicode-strings-as-grapheme-clusters/).

Add reverse-string exercise
